## Chapter 2

In [2]:
import numpy as np

__One-dimensional slicing and indexing__

In [6]:
a = np.arange(9)
a[3:7]

array([3, 4, 5, 6])

__Manipulating array shapes__

Another recurring task is flattening of arrays. Flattening in this context means
transforming a multidimensional array into a one-dimensional array

ravel() : We can accomplish flattening with the ravel() function

In [10]:
b = np.array([[[ 0, 1, 2, 3],
            [ 4, 5, 6, 7],
            [ 8, 9, 10, 11]],
            [[12, 13, 14, 15],
            [16, 17, 18, 19],
            [20, 21, 22, 23]]])
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

flatten() : The appropriately-named function, flatten() , does the same
as ravel() , but flatten() always allocates new memory, whereas ravel()
might return a view of an array.

In [11]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
b.shape = (4, 6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

transpose() : In linear algebra, it is common to transpose matrices.

In [15]:
b.transpose()

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

__Stacking arrays__

In [17]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
b = 2 * a
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

Horizontal stacking: Starting with horizontal stacking, we will form a tuple
of ndarray and give it to the hstack() function.

In [20]:
np.hstack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [21]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [23]:
np.dstack((a, b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

__Splitting arrays__

Arrays can be split vertically, horizontally, or depth-wise. The functions involved are
hsplit() , vsplit() , dsplit() , and split() . We can either split arrays into arrays
of the same shape or indicate the position after which the split should occur.

In [24]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
np.hsplit(a, 3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [26]:
np.vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [ ]:
c = np.arange(27).reshape(3, 3, 3)
np.dsplit(c, 3)

__Array attributes__

Besides the shape and dtype attributes, ndarray has a number of other attributes, as
shown in the following list:

In [30]:
b.ndim

2

In [31]:
b.size

9

In [32]:
b.itemsize

8

In [33]:
b.nbytes

72

## Chapter 3

Here in book a half of dozen examples how to do some analysis with numpy, quite useless, because of pandas usage and obsolete ideas in numpy

## Chapter 4

### Predicting temperature

__Autoregressive model with lag 1__

Fit the data to polynomials of different degrees with the polyfit

Compute values based on the polynomial obtained in the previous step.

Calculate the absolute difference between the actual temperature and the
predicted temperatures

For each polynomial fit, the calculated percentage of deltas is within 1, 2, or 3
degrees Celsius error range

In [ ]:
poly = np.polyfit( avg_temp[: cutoff - 1], avg_temp[1 : cutoff], degree)
fit = np.polyval(poly, avg_temp[cutoff:-1])
delta = np.abs(avg_temp[cutoff + 1:] - fit)

### The Autoregressive Moving Average temperature model

The Autoregressive Moving Average (ARMA) model mixes the Autoregressive
(AR) and Moving Average (MA) models. We have already discussed both models.
Informally, we can say that we have the autoregressive component with white noise
around it.

## Chapter 5

Nothing interesting

## Chapter 6

Profiling, debugging, and testing are an integral part of the development process.
You are probably familiar with the concept of unit testing. Unit tests are automated
tests written by a programmer to test his or her code. These tests could, for example,
test a function or part of a function in isolation. Only a small unit of code is tested
in each test. The benefits are increased confidence in the quality of the code,
reproducible tests and, as a side effect, more clear and correct code. Unit testing
also facilitates collaborative editing because, usually, no one understands all the
code in a complex project themselves, so unit tests prevent contributors from
breaking the existing code. Python has good support for unit testing. NumPy
adds the numpy.testing package to help NumPy code the unit testing.

__Assert functions:__

    assert_almost_equal - This raises an exception if two numbers are not equal up to a specified precision
    assert_approx_equal - This raises an exception if two numbers are not equal up to a certain significance 
    assert_array_almost_equal - This raises an exception if two arrays are not equal up to a specified precision
    assert_array_equal  - This raises an exception if two arrays are not equal
    assert_array_less   - This raises an exception if two arrays do not have the same shape and elements less
    assert_equal        - This raises an exception if two objects are not equal
    assert_raises       - This fails if a specified exception is not raised by
    assert_warns        - This fails if a specified warning is not thrown
    assert_string_equal - This asserts that two strings are equal