## Chapter 2

In [2]:
import numpy as np

__One-dimensional slicing and indexing__

In [6]:
a = np.arange(9)
a[3:7]

array([3, 4, 5, 6])

__Manipulating array shapes__

Another recurring task is flattening of arrays. Flattening in this context means
transforming a multidimensional array into a one-dimensional array

ravel() : We can accomplish flattening with the ravel() function

In [10]:
b = np.array([[[ 0, 1, 2, 3],
            [ 4, 5, 6, 7],
            [ 8, 9, 10, 11]],
            [[12, 13, 14, 15],
            [16, 17, 18, 19],
            [20, 21, 22, 23]]])
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

flatten() : The appropriately-named function, flatten() , does the same
as ravel() , but flatten() always allocates new memory, whereas ravel()
might return a view of an array.

In [11]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
b.shape = (4, 6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

transpose() : In linear algebra, it is common to transpose matrices.

In [15]:
b.transpose()

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

__Stacking arrays__

In [17]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
b = 2 * a
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

Horizontal stacking: Starting with horizontal stacking, we will form a tuple
of ndarray and give it to the hstack() function.

In [20]:
np.hstack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [21]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [23]:
np.dstack((a, b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

__Splitting arrays__

Arrays can be split vertically, horizontally, or depth-wise. The functions involved are
hsplit() , vsplit() , dsplit() , and split() . We can either split arrays into arrays
of the same shape or indicate the position after which the split should occur.

In [24]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
np.hsplit(a, 3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [26]:
np.vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [ ]:
c = np.arange(27).reshape(3, 3, 3)
np.dsplit(c, 3)

__Array attributes__

Besides the shape and dtype attributes, ndarray has a number of other attributes, as
shown in the following list: